version: "3"
services:
  postgres:
    image: "postgres:13.0"
    container_name: "pokemon_postgres"
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=pruebas
    ports:
      - 5432:5432